GET http://localhost:3000/api

### Crear cliente
POST http://localhost:3000/api/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmY4Mzc5ZWEyMjdhYzVkZWVhNmU2NyIsImVtYWlsIjoicHJ1ZWJhMTBAZ21haWwuY29tIiwiaWF0IjoxNzQ0Nzk4NjIyLCJleHAiOjE3NDQ4MDIyMjJ9.oxUCVqVVR77AE11vFQYdKNIFc_kRaGSqeEmpdnxo6O0
Content-Type: application/json

{
  "name": "Cliente Alejandro Caballero",
  "cif": "A12345555",
  "address": {
    "street": "Cañada de las merinas",
    "number": 51,
    "postal": 28232,
    "city": "Las Rozas",
    "province": "Madrid"
  }
}

### Actualizar cliente
PUT http://localhost:3000/api/client/67f79e57a7923aee1e4ba0b6
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc5YmI0YzMzMTNmODU0YjM5YTk1YyIsImVtYWlsIjoicHJ1ZWJhOUBnbWFpbC5jb20iLCJpYXQiOjE3NDQyODExMDMsImV4cCI6MTc0NDI4NDcwM30.Bt0O7cmMdSWlYfEYm6jh6LkuhoXtiGoSpT0Bf8bWONE
Content-Type: application/json

{
  "name": "Cliente actualizado",
  "cif": "D52921210",
  "address": {
    "street": "Avenida Constitución",
    "number": 88,
    "postal": 28933,
    "city": "Leganés",
    "province": "Madrid"
  }
}

### Obtener todos los clientes del usuario
GET http://localhost:3000/api/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmY4Mzc5ZWEyMjdhYzVkZWVhNmU2NyIsImVtYWlsIjoicHJ1ZWJhMTBAZ21haWwuY29tIiwiaWF0IjoxNzQ0ODAxMTU3LCJleHAiOjE3NDQ4MDQ3NTd9.a1_ovnjaYNqzeQTMR4A-mJn2uK2wlNyVfJJg0jDzmIY

### Obtener cliente por ID
GET http://localhost:3000/api/client/67ff80041675ef7d46c4b3a2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmY4Mzc5ZWEyMjdhYzVkZWVhNmU2NyIsImVtYWlsIjoicHJ1ZWJhMTBAZ21haWwuY29tIiwiaWF0IjoxNzQ0Nzk5NDI3LCJleHAiOjE3NDQ4MDMwMjd9.t2B1wf5zINf3WIp8U2wjt6Ashy0LHZR7m1VU_g9D91Y

### Archivar cliente (soft delete)
DELETE http://localhost:3000/api/client/67ff80041675ef7d46c4b3a2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc5YmI0YzMzMTNmODU0YjM5YTk1YyIsImVtYWlsIjoicHJ1ZWJhOUBnbWFpbC5jb20iLCJpYXQiOjE3NDQ3OTc2NjksImV4cCI6MTc0NDgwMTI2OX0.ed4fnpha9lGof-3v2UboX99FjMFOJ-wCW9lm7kvpBYU

### Eliminar cliente permanentemente (hard delete)
DELETE http://localhost:3000/api/client/67ff80041675ef7d46c4b3a2?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3Zjc5YmI0YzMzMTNmODU0YjM5YTk1YyIsImVtYWlsIjoicHJ1ZWJhOUBnbWFpbC5jb20iLCJpYXQiOjE3NDQ3OTc2NjksImV4cCI6MTc0NDgwMTI2OX0.ed4fnpha9lGof-3v2UboX99FjMFOJ-wCW9lm7kvpBYU
