@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTRhYTRkMjNlNTMzNDllYmNiZDYwMiIsImVtYWlsIjoibmVnZXRpNDYyNEBiZW56bm9pLmNvbSIsImlhdCI6MTc0NjE4NTM1NiwiZXhwIjoxNzQ2MTg4OTU2fQ.mzb5uclKMu0gG8NKZrkG5Vr9vEyD7A2MxXa9nzhsj8I

GET http://localhost:3000/api

### Crear cliente
POST http://localhost:3000/api/client
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Cliente Lucia Caballero",
  "cif": "B12345555",
  "address": {
    "street": "Calle Dario",
    "number": 35,
    "postal": 28232,
    "city": "Las Rozas",
    "province": "Madrid"
  }
}

### Actualizar cliente
PUT http://localhost:3000/api/client/67f79e57a7923aee1e4ba0b6
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Cliente actualizado",
  "cif": "D52921210",
  "address": {
    "street": "Avenida Constitución",
    "number": 88,
    "postal": 28933,
    "city": "Leganés",
    "province": "Madrid"
  }
}

### Obtener todos los clientes del usuario
GET http://localhost:3000/api/client
Authorization: Bearer {{token}}

### Obtener cliente por ID
GET http://localhost:3000/api/client/6814acd123e53349ebcbd615
Authorization: Bearer {{token}}

### Archivar cliente (soft delete)
DELETE http://localhost:3000/api/client/67ff80041675ef7d46c4b3a2
Authorization: Bearer {{token}}

### Eliminar cliente permanentemente (hard delete)
DELETE http://localhost:3000/api/client/67ff80041675ef7d46c4b3a2?soft=false
Authorization: Bearer {{token}}
