### Crear albarán tipo horas
POST http://localhost:3000/api/deliverynote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmY4Mzc5ZWEyMjdhYzVkZWVhNmU2NyIsImVtYWlsIjoicHJ1ZWJhMTBAZ21haWwuY29tIiwiaWF0IjoxNzQ1MTcyMDkwLCJleHAiOjE3NDUxNzU2OTB9.DGY1SiqLwrinmXglaoTuHnDRhrxpAFq86D2wu42VJpc
Content-Type: application/json

{
  "clientId": "67ff83f8ea227ac5deea6e6d",
  "projectId": "67ff8dc71c85de69b29d8e86",
  "format": "hours",
  "hours": 10,
  "description": "Cambio de luminaria",
  "workdate": "5/1/2024"
}

### Crear albarán tipo material
POST http://localhost:3000/api/deliverynote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmY4Mzc5ZWEyMjdhYzVkZWVhNmU2NyIsImVtYWlsIjoicHJ1ZWJhMTBAZ21haWwuY29tIiwiaWF0IjoxNzQ1MTcyMDkwLCJleHAiOjE3NDUxNzU2OTB9.DGY1SiqLwrinmXglaoTuHnDRhrxpAFq86D2wu42VJpc
Content-Type: application/json

{
  "clientId": "67ff83f8ea227ac5deea6e6d",
  "projectId": "67ff8dc71c85de69b29d8e86",
  "format": "material",
  "material": "Hormigón armado",
  "description": "Aplicación de hormigón armado",
  "workdate": "3/1/2024"
}

### Obtener todos los albaranes del usuario
GET http://localhost:3000/api/deliverynote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmY4Mzc5ZWEyMjdhYzVkZWVhNmU2NyIsImVtYWlsIjoicHJ1ZWJhMTBAZ21haWwuY29tIiwiaWF0IjoxNzQ1MTcyNjU4LCJleHAiOjE3NDUxNzYyNTh9.2-UjfbRWAsoEvF99zgXr4VAfyPE1-WMrsAHz4hr885Y

### Obtener albaranes firmados
GET http://localhost:3000/api/deliverynote?signed=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmY4Mzc5ZWEyMjdhYzVkZWVhNmU2NyIsImVtYWlsIjoicHJ1ZWJhMTBAZ21haWwuY29tIiwiaWF0IjoxNzQ1MTcyMDkwLCJleHAiOjE3NDUxNzU2OTB9.DGY1SiqLwrinmXglaoTuHnDRhrxpAFq86D2wu42VJpc

### Obtener albaranes pendientes
GET http://localhost:3000/api/deliverynote?signed=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmY4Mzc5ZWEyMjdhYzVkZWVhNmU2NyIsImVtYWlsIjoicHJ1ZWJhMTBAZ21haWwuY29tIiwiaWF0IjoxNzQ1MTcyMDkwLCJleHAiOjE3NDUxNzU2OTB9.DGY1SiqLwrinmXglaoTuHnDRhrxpAFq86D2wu42VJpc

### Obtener un albarán específico
GET http://localhost:3000/api/deliverynote/680536e7e1c69b47321d6040
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmY4Mzc5ZWEyMjdhYzVkZWVhNmU2NyIsImVtYWlsIjoicHJ1ZWJhMTBAZ21haWwuY29tIiwiaWF0IjoxNzQ1MTczMDMyLCJleHAiOjE3NDUxNzY2MzJ9.OCANK91ZmyiRBakblaLAMGmGxgfbIJ-j4cPRyBu7yB0
