### Crear albarán tipo horas
POST http://localhost:3000/api/deliverynote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmY4Mzc5ZWEyMjdhYzVkZWVhNmU2NyIsImVtYWlsIjoicHJ1ZWJhMTBAZ21haWwuY29tIiwiaWF0IjoxNzQ1MDAxOTA4LCJleHAiOjE3NDUwMDU1MDh9.DVpPAirV8LCw6nbfSpYDT8An-7fIZ8H5tKVAIoZMB_I
Content-Type: application/json

{
  "clientId": "67ff83f8ea227ac5deea6e6d",
  "projectId": "67ff8dc71c85de69b29d8e86",
  "format": "hours",
  "hours": 6,
  "description": "Revisión del cableado",
  "workdate": "3/1/2024"
}

### Crear albarán tipo material
POST http://localhost:3000/api/deliverynote
Authorization: Bearer token
Content-Type: application/json

{
  "clientId": "MONGO_CLIENT_ID",
  "projectId": "MONGO_PROJECT_ID",
  "format": "material",
  "material": "Hormigón armado",
  "description": "Aplicación de hormigón armado",
  "workdate": "3/1/2024"
}
