@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmY4Mzc5ZWEyMjdhYzVkZWVhNmU2NyIsImVtYWlsIjoicHJ1ZWJhMTBAZ21haWwuY29tIiwiaWF0IjoxNzQ2MTgyODgyLCJleHAiOjE3NDYxODY0ODJ9._x-6xQkBVS4ScmjYxUrRspd4zl5tHFsQxKNqvBMfMO0

### Crear albaran tipo horas
POST http://localhost:3000/api/deliverynote
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "clientId": "67ff83f8ea227ac5deea6e6d",
  "projectId": "67ff8dc71c85de69b29d8e86",
  "format": "hours",
  "hours": 10,
  "description": "Cambio de luminaria",
  "workdate": "5/1/2024"
}

### Crear albaran tipo material
POST http://localhost:3000/api/deliverynote/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "clientId": "67ff83f8ea227ac5deea6e6d",
  "projectId": "67ff8dc71c85de69b29d8e86",
  "format": "material",
  "material": "Hormigón armado",
  "description": "Aplicación de hormigón armado",
  "workdate": "3/1/2024"
}

### Obtener todos los albaranes del usuario
GET http://localhost:3000/api/deliverynote
Authorization: Bearer {{token}}

### Obtener albaranes firmados
GET http://localhost:3000/api/deliverynote?signed=true
Authorization: Bearer {{token}}

### Obtener albaranes pendientes
GET http://localhost:3000/api/deliverynote?signed=false
Authorization: Bearer {{token}}

### Obtener un albarán específico
GET http://localhost:3000/api/deliverynote/680536e7e1c69b47321d6040
Authorization: Bearer {{token}}

### Generar y ver PDF de un albarán
GET http://localhost:3000/api/deliverynote/pdf/680536e7e1c69b47321d6040
Authorization: Bearer {{token}}

### Firmar albarán (subir imagen firma)
PATCH http://localhost:3000/api/deliverynote/sign/680536e7e1c69b47321d6040
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="sign"; filename="firma.png"
Content-Type: image/png

< ../images/Logo-U-tad 1.png
--boundary123--

### Borrar un albarán que no este firmado
DELETE http://localhost:3000/api/deliverynote/68029e2cde4aed9d99f61b6b
Authorization: Bearer {{token}}
