GET http://localhost:3000/api

### Registro Valido
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "prueba5@gmail.com",
  "password": "contraseña123"
}

### Validacion
POST http://localhost:3000/api/user/validation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTdlZDlhNTYxNGIzYzllYzk0MWM3MyIsImVtYWlsIjoicHJ1ZWJhNUBnbWFpbC5jb20iLCJpYXQiOjE3NDMyNTI4OTAsImV4cCI6MTc0MzI1NjQ5MH0.MBMS4BiYUY9037dqiUvKDTux4jJF68QUcvXOWmxSioM
Content-Type: application/json

{
  "code": "169459"
}

### Login
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "prueba5@gmail.com",
  "password": "contraseña123"
}

### Onboarding - Datos personales
PUT http://localhost:3000/api/user/register
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTdlZDlhNTYxNGIzYzllYzk0MWM3MyIsImVtYWlsIjoicHJ1ZWJhNUBnbWFpbC5jb20iLCJpYXQiOjE3NDMyNTI5MTYsImV4cCI6MTc0MzI1NjUxNn0.MY_teuCIVcRaN9zaVsiNlVp6yn7TgJHfPqb2aOGMMaQ
Content-Type: application/json

{
  "nombre": "Carlos",
  "apellidos": "Alonso Parera",
  "nif": "12345678D"
}

### Onboarding - Empresa normal
PATCH http://localhost:3000/api/user/company
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTdlZDlhNTYxNGIzYzllYzk0MWM3MyIsImVtYWlsIjoicHJ1ZWJhNUBnbWFpbC5jb20iLCJpYXQiOjE3NDMyNTI5MTYsImV4cCI6MTc0MzI1NjUxNn0.MY_teuCIVcRaN9zaVsiNlVp6yn7TgJHfPqb2aOGMMaQ
Content-Type: application/json

{
  "name": "Servitop, SL.",
  "cif": "B12345678",
  "street": "Carlos V",
  "number": 22,
  "postal": 28936,
  "city": "Móstoles",
  "province": "Madrid",
  "esAutonomo": false
}


### Onboarding - Autonomo
PATCH http://localhost:3000/api/user/company
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTdlOTQ5MzMzNTk1NjE4MGMxYjIxOSIsImVtYWlsIjoicHJ1ZWJhM0BnbWFpbC5jb20iLCJpYXQiOjE3NDMyNTE4MzAsImV4cCI6MTc0MzI1NTQzMH0.sCDqM4wfOTI3v3QPvBIOejxKm3QPVuEtLAliyqUJ9RA
Content-Type: application/json

{
  "street": "Calle Victoria 33",
  "number": 7,
  "postal": 28922,
  "city": "Alcorcón",
  "province": "Madrid",
  "esAutonomo": true
}

### Subir logo a Pinata
PATCH http://localhost:3000/api/user/logo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTdlZDlhNTYxNGIzYzllYzk0MWM3MyIsImVtYWlsIjoicHJ1ZWJhNUBnbWFpbC5jb20iLCJpYXQiOjE3NDMyNTQ5OTEsImV4cCI6MTc0MzI1ODU5MX0.uYVdueiL_YWjj-gYJxxdjEuw6zJMWrrc1glzbSbGGIY
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="logo"; filename="Logo-U-tad 1.png"
Content-Type: image/png

< ../images/Logo-U-tad 1.png
--boundary123--
