@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTRhYTRkMjNlNTMzNDllYmNiZDYwMiIsImVtYWlsIjoibmVnZXRpNDYyNEBiZW56bm9pLmNvbSIsImlhdCI6MTc0NjI5NzUzMiwiZXhwIjoxNzQ2MzAxMTMyfQ.fT7utGSoNQgAzeQkvWhqC1DxTrGpIen3fOh_ylxFsow

### Crear proyecto
POST http://localhost:3000/api/project
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Proyecto Uno",
  "projectCode": "ACS-03",
  "email": "lucab@gmail.com",
  "code": "PLCP001",
  "clientId": "6814acd123e53349ebcbd615",
  "address": {
    "street": "Avenida Atenas",
    "number": 5,
    "postal": 28232,
    "city": "Madrid",
    "province": "Madrid"
  }
}

### Actualizar proyecto
PUT http://localhost:3000/api/project/67ff8541d0fd65645250284f
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "obra",
  "projectCode": "100000",
  "email": "mimail@gmail.com",
  "code": "00001-01",
  "clientId": "67ff8379ea227ac5deea6e67",
  "address": {
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  },
  "notes": "Notas del proyecto"
}

### Obtener todos los proyectos
GET http://localhost:3000/api/project
Authorization: Bearer {{token}}

### Obtener un proyecto concreto
GET http://localhost:3000/api/project/one/6814ad4923e53349ebcbd619
Authorization: Bearer {{token}}

### Archivar proyecto (soft delete)
DELETE http://localhost:3000/api/project/6814ad4923e53349ebcbd619
Authorization: Bearer {{token}}

### Borrar proyecto permanentemente (hard delete)
DELETE http://localhost:3000/api/project/67ff8a4976f44b7c2fea3b6f?soft=false
Authorization: Bearer {{token}}

### Obtener proyectos archivados
GET http://localhost:3000/api/project/archive
Authorization: Bearer {{token}}

### Restaurar proyecto archivado
PATCH http://localhost:3000/api/project/restore/6814ad4923e53349ebcbd619
Authorization: Bearer {{token}}
