@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTRhYTRkMjNlNTMzNDllYmNiZDYwMiIsImVtYWlsIjoibmVnZXRpNDYyNEBiZW56bm9pLmNvbSIsImlhdCI6MTc0NjI3NDAzNCwiZXhwIjoxNzQ2Mjc3NjM0fQ.ojIaeOSS0AEZOgFrqZpJaAHn71XlDYA5OJ020sH5LK8

GET http://localhost:3000/api

### Registro Valido
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "prueba124@gmail.com",
  "password": "contraseña123"
}

### Validacion
POST http://localhost:3000/api/user/validation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTRhYTRkMjNlNTMzNDllYmNiZDYwMiIsImVtYWlsIjoibmVnZXRpNDYyNEBiZW56bm9pLmNvbSIsImlhdCI6MTc0NjE4NDc4MSwiZXhwIjoxNzQ2MTg4MzgxfQ.XI_Sz3fHjXyQxowdDydJmSqk1EKgUWTHn-mHoFkp-sg
Content-Type: application/json

{
  "code": "322032"
}

### Login
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "negeti4624@benznoi.com",
  "password": "nuevacontraseña123"
}

### Onboarding - Datos personales
PUT http://localhost:3000/api/user/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Alejandro",
  "apellidos": "Caballero Poveda",
  "nif": "12345678J"
}

### Onboarding - Empresa normal
PATCH http://localhost:3000/api/user/company
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "U-tad, SL.",
  "cif": "J12345678",
  "street": "Carlos V",
  "number": 22,
  "postal": 28232,
  "city": "Las Rozas",
  "province": "Madrid",
  "esAutonomo": false
}


### Onboarding - Autonomo
PATCH http://localhost:3000/api/user/company
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "street": "Calle Pandora",
  "number": 1,
  "postal": 28232,
  "city": "Las Rozas",
  "province": "Madrid",
  "esAutonomo": true
}

### Subir logo a Pinata
PATCH http://localhost:3000/api/user/logo
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="logo"; filename="Logo-U-tad 1.png"
Content-Type: image/png

< ../images/mbappe.jpg
--boundary123--

### GET datos del usuario
GET http://localhost:3000/api/user
Authorization: Bearer {{token}}

### Soft delete
DELETE http://localhost:3000/api/user
Authorization: Bearer {{token}}

### Hard delete
DELETE http://localhost:3000/api/user?soft=false
Authorization: Bearer {{token}}

### Recuperar contraseña
POST http://localhost:3000/api/user/recover
Content-Type: application/json

{
  "email": "negeti4624@benznoi.com"
}

### Cambiar contraseña tras recuperación
PATCH http://localhost:3000/api/user/password
Content-Type: application/json

{
  "email": "negeti4624@benznoi.com",
  "code": "645301",
  "password": "nuevacontraseña123"
}

