@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZmY4Mzc5ZWEyMjdhYzVkZWVhNmU2NyIsImVtYWlsIjoicHJ1ZWJhMTBAZ21haWwuY29tIiwiaWF0IjoxNzQ1OTUyMDgyLCJleHAiOjE3NDU5NTU2ODJ9.1Jy5YZgO5nxC-YLhjca9_yCdB0hihrxpVj33KaXiRjI

GET http://localhost:3000/api

### Registro Valido
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "prueba11@gmail.com",
  "password": "contraseña123"
}

### Validacion
POST http://localhost:3000/api/user/validation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MTExZTkwZTI0NTM5MjZmZDQ1OGE5MCIsImVtYWlsIjoicHJ1ZWJhMTFAZ21haWwuY29tIiwiaWF0IjoxNzQ1OTUyNDAwLCJleHAiOjE3NDU5NTYwMDB9.H67cQpereJIFgabPWCmrJTwA_OBD1IldTdd3dpmpqkc
Content-Type: application/json

{
  "code": "463704"
}

### Login
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
  "email": "prueba11@gmail.com",
  "password": "contraseña123"
}

### Onboarding - Datos personales
PUT http://localhost:3000/api/user/register
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "nombre": "Cristiano",
  "apellidos": "Ronaldo Aveiro",
  "nif": "12345678S"
}

### Onboarding - Empresa normal
PATCH http://localhost:3000/api/user/company
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "U-tad, SL.",
  "cif": "J12345678",
  "street": "Carlos V",
  "number": 22,
  "postal": 28232,
  "city": "Las Rozas",
  "province": "Madrid",
  "esAutonomo": false
}


### Onboarding - Autonomo
PATCH http://localhost:3000/api/user/company
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "street": "Calle Bicho",
  "number": 7,
  "postal": 28232,
  "city": "Las Rozas",
  "province": "Madrid",
  "esAutonomo": true
}

### Subir logo a Pinata
PATCH http://localhost:3000/api/user/logo
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary123

--boundary123
Content-Disposition: form-data; name="logo"; filename="Logo-U-tad 1.png"
Content-Type: image/png

< ../images/cristiano.png
--boundary123--

### GET datos del usuario
GET http://localhost:3000/api/user
Authorization: Bearer {{token}}

### Soft delete
DELETE http://localhost:3000/api/user
Authorization: Bearer {{token}}

### Hard delete
DELETE http://localhost:3000/api/user?soft=false
Authorization: Bearer {{token}}

### Recuperar contraseña
POST http://localhost:3000/api/user/recover
Content-Type: application/json

{
  "email": "prueba8@gmail.com"
}

### Cambiar contraseña tras recuperación
PATCH http://localhost:3000/api/user/password
Content-Type: application/json

{
  "email": "prueba7@gmail.com",
  "code": "448841",
  "password": "nuevacontraseña123"
}

