GET http://localhost:3000/api

###
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "alex@gmail.com",
  "password": "mipasswordsegura"
}

###
POST http://localhost:3000/api/user/validation
Authorization: Bearer TU_TOKEN_JWT
Content-Type: application/json

{
  "code": "491117"
}
