GET http://localhost:3000/api

###
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
  "email": "alex@gmail.com",
  "password": "mipasswordsegura"
}

###
POST http://localhost:3000/api/user/validation
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3ZTNkZjM1NDEwNzI0MThlZTlkMTY1MiIsImVtYWlsIjoiYWxleEBnbWFpbC5jb20iLCJpYXQiOjE3NDI5ODcwNjEsImV4cCI6MTc0Mjk5MDY2MX0.32aYZxHfnbIzlhH3_7ixvIlfJuNBWHz_zftJ_3MscLs
Content-Type: application/json

{
  "code": "645103"
}
